wishlist_list_products:
    path: /wishlist
    methods: [GET]
    defaults:
        _controller: sylius_wishlist_plugin.controller.action.list_wishlist_products

        
wishlist_export_selected_to_csv:
    path: /wishlists/{wishlistId}/export-csv
    methods: [POST]
    defaults:
        _controller: sylius_wishlist_plugin.controller.action.export_selected_to_csv
        _sylius:
            csrf_protection: false

wishlist_export_selected_products_to_csv:
    path: /wishlists/{wishlistId}/export-selected-csv
    methods: [POST]
    defaults:
        _controller: sylius_wishlist_plugin.controller.action.export_selected_products_to_csv
        _sylius:
            csrf_protection: false

wishlist_export_to_pdf:
    path: /wishlists/{wishlistId}/export-pdf
    methods: [POST]
    defaults:
        _controller: sylius_wishlist_plugin.controller.action.export_wishlist_to_pdf
        _sylius:
            csrf_protection: false

wishlist_import_from_csv:
    path: /wishlists/import-from-csv
    methods: [GET, POST]
    defaults:
        _controller: sylius_wishlist_plugin.controller.action.import_wishlist_from_csv


wishlist_render_header_template:
    path: /wishlist/header-template
    defaults:
        _controller: sylius_wishlist_plugin.controller.action.render_header_template


wishlist_list_wishlists:
    path: /wishlists
    defaults:
        _controller: sylius_wishlist_plugin.controller.action.list_wishlists


wishlist_remove_wishlist:
    path: /wishlists/{id}/remove
    methods: [GET, POST, DELETE]
    defaults:
        _controller: sylius_wishlist_plugin.controller.wishlist::deleteAction
        _sylius:
            csrf_protection: false
            flash: sylius_wishlist_plugin.ui.remove_wishlist
            redirect:
                route: wishlist_list_wishlists


wishlist_show_chosen_wishlist:
    path: /wishlists/{wishlistId}
    defaults:
        _controller: sylius_wishlist_plugin.controller.action.show_chosen_wishlist
