sylius_wishlist_plugin_shop_no_prefix:
  resource: "@SyliusWishlistPlugin/config/routes/shop.yaml"
  name_prefix: 'sylius_wishlist_plugin_shop_'

sylius_wishlist_plugin_shop:
  resource: "@SyliusWishlistPlugin/config/routes/shop.yaml"
  name_prefix: 'sylius_wishlist_plugin_shop_locale_'
  prefix: /{_locale}
  requirements:
    _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

