sylius_twig_hooks:
    hooks:
        'sylius_shop.common.add_to_wishlist.single':
            content:
                component: 'sylius_shop:wishlist:add_to_wishlist_button'
                props:
                    template: '@SyliusWishlistPlugin/common/add_to_wishlist/single.html.twig'
                    productId: '@=_context.product.getId()'
                priority: 0
        'sylius_shop.common.add_to_wishlist.multiple':
            content:
                template: '@SyliusWishlistPlugin/common/add_to_wishlist/multiple.html.twig'
                priority: 0
        'sylius_shop.common.add_to_wishlist.multiple.toggle':
            content:
                template: '@SyliusWishlistPlugin/common/add_to_wishlist/multiple/toggle.html.twig'
                priority: 0
        'sylius_shop.common.add_to_wishlist.multiple.items':
            content:
                template: '@SyliusWishlistPlugin/common/add_to_wishlist/multiple/items.html.twig'
                priority: 0
        'sylius_shop.common.add_to_wishlist.multiple.items.item':
            content:
                component: 'sylius_shop:wishlist:add_to_selected_wishlist_button'
                props:
                    template: '@SyliusWishlistPlugin/common/add_to_wishlist/multiple/item.html.twig'
                    wishlistId: '@=_context.wishlist.getId()'
                    productId: '@=_context.product.getId()'
                priority: 0
