sylius_twig_hooks:
    hooks:
        'sylius_shop.product.show.add_to_wishlist.single':
            content:
                template: '@SyliusWishlistPlugin/product/show/add_to_wishlist/single.html.twig'
                priority: 0
        'sylius_shop.product.show.add_to_wishlist.multiple':
            content:
                template: '@SyliusWishlistPlugin/product/show/add_to_wishlist/multiple.html.twig'
                priority: 0
        'sylius_shop.product.show.add_to_wishlist.multiple.toggle':
            content:
                template: '@SyliusWishlistPlugin/product/show/add_to_wishlist/multiple/toggle.html.twig'
                priority: 0
        'sylius_shop.product.show.add_to_wishlist.multiple.items':
            content:
                template: '@SyliusWishlistPlugin/product/show/add_to_wishlist/multiple/items.html.twig'
                priority: 0
        'sylius_shop.product.show.add_to_wishlist.multiple.items.item':
            content:
                template: '@SyliusWishlistPlugin/product/show/add_to_wishlist/multiple/item.html.twig'
                priority: 0
